import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import { trpc } from '@/utils/trpc'

export default function Home() {
  const { data: session } = useSession()
  const req = trpc.hello.useQuery({ text: 'john' })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Helolo {req.data?.greeting}</p>
        <img
          src={session?.user?.image || ''}
          alt="profile"
          referrerPolicy="no-referrer"
        />

        {session && (
          <button onClick={() => signOut()}>
            Sign out
            {session.user?.name}
          </button>
        )}

        {!session && <button onClick={() => signIn('google')}>Sign In</button>}
      </main>
    </>
  )
}
